# Generated by Django 2.2.5 on 2021-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211103_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('GITHUB', 'GITHUB'), ('KAKAO', 'KAKAO')], default='EMAIL', max_length=20),
        ),
    ]
